//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ShopEntities : DbContext
    {
        public ShopEntities()
            : base("name=ShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product_in_shop> Product_in_shop { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Shop> Shops { get; set; }
        public virtual DbSet<Sort> Sorts { get; set; }
    
        public virtual ObjectResult<getShopsInfo_Result> getShopsInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getShopsInfo_Result>("getShopsInfo");
        }
    
        public virtual ObjectResult<getShopsInfo_Result> query2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getShopsInfo_Result>("query2");
        }
    
        public virtual ObjectResult<firstQuery_Result> firstQuery(Nullable<int> number)
        {
            var numberParameter = number.HasValue ?
                new ObjectParameter("number", number) :
                new ObjectParameter("number", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<firstQuery_Result>("firstQuery", numberParameter);
        }
    }
}
