//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Shop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop()
        {
            this.Product_in_shop = new HashSet<Product_in_shop>();
        }

        [Required(ErrorMessage = "Поле является обязательным")]
        [Display(Name = "Номер магазина")]
        public int number { get; set; }

        [Required(ErrorMessage = "Поле является обязательным")]
        [Display(Name = "Название магазина")]
        public string name { get; set; }

        [Required(ErrorMessage = "Поле является обязательным")]
        [Display(Name = "Адрес")]
        public string address { get; set; }

        [Required(ErrorMessage = "Поле является обязательным")]
        [Display(Name = "Площадь")]
        [Range(double.Epsilon, double.MaxValue, ErrorMessage = "Площадь должна быть больше 0")]
        public double square { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_in_shop> Product_in_shop { get; set; }
    }
}
